industry_lut = {'Aerospace & Defense': 'Aerospace/Defense',
 'Agricultural Inputs': 'Farming/Agriculture',
 'Airlines': 'Air Transport',
 'Airports & Air Services': 'Business & Consumer Services',
 'Aluminum': 'Metals & Mining',
 'Apparel Manufacturing': 'Apparel',
 'Apparel Retail': 'Retail (General)',
 'Asset Management': 'Investments & Asset Management',
 'Auto & Truck Dealerships': 'Retail (Automotive)',
 'Auto Manufacturers': 'Auto & Truck',
 'Auto Parts': 'Auto Parts',
 'Banks—Diversified': 'Bank (Money Center)',
 'Banks—Regional': 'Banks (Regional)',
 'Beverages—Brewers': 'Beverage (Soft)',
 'Beverages—Non-Alcoholic': 'Beverage (Alcoholic)',
 'Beverages—Wineries & Distilleries': 'Beverage (Alcoholic)',
 'Biotechnology': 'Drugs (Biotechnology)',
 'Broadcasting': 'Broadcasting',
 'Building Materials': 'Building Materials',
 'Building Products & Equipment': 'Office Equipment & Services',
 'Capital Markets': 'Brokerage & Investment Banking',
 'Chemicals': 'Chemical (Basic)',
 'Communication Equipment': 'Telecom. Equipment',
 'Computer Hardware': 'Computers/Peripherals',
 'Confectioners': 'Food Processing',
 'Conglomerates': 'Diversified',
 'Consulting Services': 'Computer Services',
 'Consumer Electronics': 'Computers/Peripherals',
 'Copper': 'Metals & Mining',
 'Credit Services': 'Business & Consumer Services',
 'Department Stores': 'Retail (General)',
 'Diagnostics & Research': 'Heathcare Information and Technology',
 'Discount Stores': 'Retail (General)',
 'Drug Manufacturers - Major': 'Drugs (Pharmaceutical)',
 'Drug Manufacturers—General': 'Drugs (Pharmaceutical)',
 'Drug Manufacturers—Specialty & Generic': 'Drugs (Biotechnology)',
 'Education & Training Services': 'Education',
 'Electrical Equipment & Parts': 'Electrical Equipment',
 'Electronic Components': 'Electronics (General)',
 'Electronic Gaming & Multimedia': 'Electronics (Consumer & Office)',
 'Engineering & Construction': 'Engineering/Construction',
 'Entertainment': 'Entertainment',
 'Farm & Heavy Construction Machinery': 'Food Processing',
 'Farm Products': 'Food Wholesalers',
 'Financial Data & Stock Exchanges': 'Financial Svcs. (Non-bank & Insurance)',
 'Food Distribution': 'Food Wholesalers',
 'Footwear & Accessories': 'Shoe',
 'Gold': 'Metals & Mining',
 'Grocery Stores': 'Food Wholesalers',
 'Healthcare Plans': 'Healthcare Support Services',
 'Household & Personal Products': 'Household Products',
 'Industrial Distribution': 'Retail (Distributors)',
 'Information Technology Services': 'Information Services',
 'Infrastructure Operations': 'Real Estate (Operations & Services)',
 'Insurance—Diversified': 'Insurance (General)',
 'Insurance—Life': 'Insurance (Life)',
 'Insurance—Property & Casualty': 'Insurance (Prop/Cas.)',
 'Insurance—Reinsurance': 'Reinsurance',
 'Integrated Freight & Logistics': 'Transportation',
 'Internet Content & Information': 'Software (Internet)',
 'Internet Retail': 'Retail (Online)',
 'Leisure': 'Entertainment',
 'Lodging': 'Hotel/Gaming',
 'Luxury Goods': 'Retail (Special Lines)',
 'Medical Care Facilities': 'Hospitals/Healthcare Facilities',
 'Medical Devices': 'Healthcare Products',
 'Medical Distribution': 'Healthcare Support Services',
 'Medical Instruments & Supplies': 'Healthcare Products',
 'Mortgage Finance': 'Financial Svcs. (Non-bank & Insurance)',
 'Oil & Gas E&P': 'Oil/Gas (Production and Exploration)',
 'Oil & Gas Equipment & Services': 'Office Equipment & Services',
 'Oil & Gas Integrated': 'Oil/Gas (Integrated)',
 'Oil & Gas Midstream': 'Oil/Gas (Production and Exploration)',
 'Oil & Gas Refining & Marketing': 'Oil/Gas Distribution',
 'Other Industrial Metals & Mining': 'Metals & Mining',
 'Packaged Foods': 'Food Processing',
 'Packaging & Containers': 'Packaging & Container',
 'Paper & Paper Products': 'Paper/Forest Products',
 'Personal Services': 'Information Services',
 'Pharmaceutical Retailers': 'Drugs (Pharmaceutical)',
 'Publishing': 'Publishing & Newspapers',
 'REIT—Healthcare Facilities': 'R.E.I.T.',
 'REIT—Industrial': 'R.E.I.T.',
 'REIT—Office': 'R.E.I.T.',
 'REIT—Specialty': 'R.E.I.T.',
 'Railroads': 'Transportation (Railroads)',
 'Real Estate Services': 'Real Estate (Operations & Services)',
 'Real Estate—Development': 'Real Estate (Development)',
 'Recreational Vehicles': 'Auto & Truck',
 'Rental & Leasing Services': 'Real Estate (Operations & Services)',
 'Residential Construction': 'Homebuilding',
 'Resorts & Casinos': 'Recreation',
 'Restaurants': 'Restaurant/Dining',
 'Semiconductors': 'Semiconductor',
 'Software—Application': 'Software (System & Application)',
 'Software—Infrastructure': 'Software (System & Application)',
 'Specialty Business Services': 'Business & Consumer Services',
 'Specialty Chemicals': 'Chemical (Specialty)',
 'Specialty Industrial Machinery': 'Machinery',
 'Specialty Retail': 'Retail (Special Lines)',
 'Staffing & Employment Services': 'Business & Consumer Services',
 'Steel': 'Steel',
 'Telecom Services': 'Telecom. Services',
 'Thermal Coal': 'Coal & Related Energy',
 'Tobacco': 'Tobacco',
 'Tools & Accessories': 'Total Market',
 'Travel Services': 'Recreation',
 'Trucking': 'Trucking',
 'Uranium': 'Metals & Mining',
 'Utilities—Diversified': 'Diversified',
 'Utilities—Independent Power Producers': 'Utility (General)',
 'Utilities—Regulated Electric': 'Utility (General)',
 'Utilities—Regulated Gas': 'Utility (General)',
 'Utilities—Regulated Water': 'Utility (Water)',
 'Utilities—Renewable': 'Green & Renewable Energy'
}
