stocks_dict = {'Consumer Discretionary': [{'currency': 'USD',
                             'name': 'Carnival Corporation',
                             'ticker': 'CCL'},
                            {'currency': 'USD',
                             'name': 'Revlon, Inc. New',
                             'ticker': 'REV'},
                            {'currency': 'USD',
                             'name': 'Ford Motor Company',
                             'ticker': 'F'},
                            {'currency': 'USD',
                             'name': 'American Eagle Outfitters, Inc.',
                             'ticker': 'AEO'},
                            {'currency': 'USD',
                             'name': 'Hibbett Sports, Inc.',
                             'ticker': 'HIBB'},
                            {'currency': 'USD',
                             'name': 'Acorn International, Inc.',
                             'ticker': 'ATV'},
                            {'currency': 'USD',
                             'name': 'Intercontinental Hotels Group',
                             'ticker': 'IHG'},
                            {'currency': 'INR',
                             'name': 'BOSCH LTD.',
                             'ticker': 'BOSCHLTD.BO'},
                            {'currency': 'USD',
                             'name': 'Red Lions Hotels Corporation',
                             'ticker': 'RLH'},
                            {'currency': 'USD',
                             'name': 'LCI Industries',
                             'ticker': 'LCII'},
                            {'currency': 'USD',
                             'name': 'Comcast Corporation',
                             'ticker': 'CMCSA'},
                            {'currency': 'USD',
                             'name': 'Smith & Wesson Brands, Inc.',
                             'ticker': 'SWBI'},
                            {'currency': 'USD',
                             'name': "Macy's Inc",
                             'ticker': 'M'},
                            {'currency': 'USD',
                             'name': 'Yum! Brands, Inc.',
                             'ticker': 'YUM'},
                            {'currency': 'USD',
                             'name': 'LOOKERS',
                             'ticker': 'LKKRF'},
                            {'currency': 'USD',
                             'name': 'Target Corporation',
                             'ticker': 'TGT'},
                            {'currency': 'USD',
                             'name': 'Aptiv PLC',
                             'ticker': 'APTV'},
                            {'currency': 'INR',
                             'name': 'BATA INDIA LTD.',
                             'ticker': 'BATAINDIA.BO'},
                            {'currency': 'INR',
                             'name': 'MAHINDRA & MAHINDRA LTD.',
                             'ticker': 'M&M.BO'},
                            {'currency': 'INR',
                             'name': 'HERO MOTOCORP LTD.',
                             'ticker': 'HEROMOTOCO.BO'},
                            {'currency': 'USD',
                             'name': "Wendy's Company (The)",
                             'ticker': 'WEN'},
                            {'currency': 'GBp',
                             'name': 'HOSTELWORLD GROUP PLC ORD EUR0.',
                             'ticker': 'HSW.L'},
                            {'currency': 'GBp',
                             'name': 'WHITBREAD PLC ORD 76 122/153P',
                             'ticker': 'WTB.L'},
                            {'currency': 'INR',
                             'name': 'MARUTI SUZUKI INDIA LTD.',
                             'ticker': 'MARUTI.BO'},
                            {'currency': 'INR',
                             'name': 'BAJAJ AUTO LTD.',
                             'ticker': 'BAJAJ-AUTO.BO'},
                            {'currency': 'GBp',
                             'name': 'PEARSON PLC ORD 25P',
                             'ticker': 'PSON.L'},
                            {'currency': 'BRL',
                             'name': 'B2W DIGITAL ON      NM',
                             'ticker': 'BTOW3.SA'},
                            {'currency': 'GBp',
                             'name': 'ON THE BEACH GROUP PLC ORD 1P',
                             'ticker': 'OTB.L'},
##                            {'currency': 'USD',
##                             'name': 'Error',
##                             'ticker': '500570.BO'},
                            {'currency': 'CNY',
                             'name': 'CHINA TOURISM GROUP DUTY FREE C',
                             'ticker': '601888.SS'},
                            {'currency': 'BRL',
                             'name': 'MAGAZ LUIZA ON      NM',
                             'ticker': 'MGLU3.SA'},
                            {'currency': 'GBp',
                             'name': 'NEXT PLC ORD 10P',
                             'ticker': 'NXT.L'},
                            {'currency': 'USD',
                             'name': 'Build-A-Bear Workshop, Inc.',
                             'ticker': 'BBW'},
                            {'currency': 'INR',
                             'name': 'JUBILANT FOODWORKS',
                             'ticker': 'JUBLFOOD.NS'},
##                            {'currency': 'USD',
##                             'name': 'Error',
##                             'ticker': 'COGN3.SA'},
                            {'currency': 'CNY',
                             'name': 'MIDEA GROUP CO LTD',
                             'ticker': '000333.SZ'},
                            {'currency': 'BRL',
                             'name': 'LOCALIZA    ON      NM',
                             'ticker': 'RENT3.SA'},
                            {'currency': 'USD',
                             'name': 'Burlington Stores, Inc.',
                             'ticker': 'BURL'},
                            {'currency': 'USD',
                             'name': 'Imax Corporation',
                             'ticker': 'IMAX'},
                            {'currency': 'BRL',
                             'name': 'LOJAS AMERICPN      N1',
                             'ticker': 'LAME4.SA'},
                            {'currency': 'USD',
                             'name': 'China Automotive Systems, Inc.',
                             'ticker': 'CAAS'},
                            {'currency': 'CAD',
                             'name': 'DOLLARAMA INC',
                             'ticker': 'DOL.TO'},
                            {'currency': 'USD',
                             'name': 'Chipotle Mexican Grill, Inc.',
                             'ticker': 'CMG'},
                            {'currency': 'USD',
                             'name': "Domino's Pizza Inc",
                             'ticker': 'DPZ'},
                            {'currency': 'USD',
                             'name': 'Harley-Davidson, Inc.',
                             'ticker': 'HOG'},
                            {'currency': 'USD',
                             'name': 'lululemon athletica inc.',
                             'ticker': 'LULU'},
                            {'currency': 'BRL',
                             'name': 'LOJAS RENNERON      NM',
                             'ticker': 'LREN3.SA'},
                            {'currency': 'USD',
                             'name': 'Restaurant Brands International',
                             'ticker': 'QSR'},
                            {'currency': 'USD',
                             'name': 'Nike, Inc.',
                             'ticker': 'NKE'},
                            {'currency': 'USD',
                             'name': 'CarMax Inc',
                             'ticker': 'KMX'},
                            {'currency': 'USD',
                             'name': 'Mattel, Inc.',
                             'ticker': 'MAT'},
                            {'currency': 'USD',
                             'name': 'Best Buy Co., Inc.',
                             'ticker': 'BBY'},
                            {'currency': 'USD',
                             'name': 'Tailored Brands, Inc.',
                             'ticker': 'TLRD'},
##                            {'currency': 'USD',
##                             'name': 'Error',
##                             'ticker': '500114.BO'},
                            {'currency': 'USD',
                             'name': 'Amazon.com, Inc.',
                             'ticker': 'AMZN'},
                            {'currency': 'USD',
                             'name': 'BorgWarner Inc.',
                             'ticker': 'BWA'},
                            {'currency': 'USD',
                             'name': 'Tesla, Inc.',
                             'ticker': 'TSLA'},
                            {'currency': 'USD',
                             'name': 'Texas Roadhouse, Inc.',
                             'ticker': 'TXRH'},
                            {'currency': 'USD',
                             'name': 'The Cheesecake Factory Incorpor',
                             'ticker': 'CAKE'},
                            {'currency': 'USD',
                             'name': 'Marriott International',
                             'ticker': 'MAR'},
                            {'currency': 'USD',
                             'name': 'Costco Wholesale Corporation',
                             'ticker': 'COST'},
                            {'currency': 'USD',
                             'name': 'New Oriental Education & Techno',
                             'ticker': 'EDU'},
                            {'currency': 'USD',
                             'name': 'Toyota Motor Corporation',
                             'ticker': 'TM'},
                            {'currency': 'USD',
                             'name': 'Core-Mark Holding Company, Inc.',
                             'ticker': 'CORE'},
                            {'currency': 'USD',
                             'name': 'H&R Block, Inc.',
                             'ticker': 'HRB'},
                            {'currency': 'USD',
                             'name': 'Ritchie Bros. Auctioneers Incor',
                             'ticker': 'RBA'},
                            {'currency': 'USD',
                             'name': 'General Motors Company',
                             'ticker': 'GM'},
                            {'currency': 'USD',
                             'name': 'Estee Lauder Companies, Inc. (T',
                             'ticker': 'EL'},
                            {'currency': 'USD',
                             'name': 'Sirius XM Holdings Inc.',
                             'ticker': 'SIRI'},
                            {'currency': 'USD',
                             'name': 'Honda Motor Company, Ltd.',
                             'ticker': 'HMC'},
                            {'currency': 'USD',
                             'name': 'Gap, Inc. (The)',
                             'ticker': 'GPS'},
                            {'currency': 'USD',
                             'name': 'Hyatt Hotels Corporation',
                             'ticker': 'H'},
                            {'currency': 'USD',
                             'name': 'Dollar Tree, Inc.',
                             'ticker': 'DLTR'},
                            {'currency': 'USD',
                             'name': 'Dollar General Corporation',
                             'ticker': 'DG'},
                            {'currency': 'USD',
                             'name': 'Abercrombie & Fitch Company',
                             'ticker': 'ANF'},
                            {'currency': 'USD',
                             'name': 'Hasbro, Inc.',
                             'ticker': 'HAS'},
                            {'currency': 'USD',
                             'name': 'Las Vegas Sands Corp.',
                             'ticker': 'LVS'},
                            {'currency': 'USD',
                             'name': 'Under Armour, Inc.',
                             'ticker': 'UAA'},
                            {'currency': 'USD',
                             'name': 'Crescent Point Energy Corporati',
                             'ticker': 'CPG'},
                            {'currency': 'USD',
                             'name': 'Container Store (The)',
                             'ticker': 'TCS'},
                            {'currency': 'USD',
                             'name': "Lands' End, Inc.",
                             'ticker': 'LE'},
                            {'currency': 'USD',
                             'name': 'Bed Bath & Beyond Inc.',
                             'ticker': 'BBBY'},
                            {'currency': 'USD',
                             'name': "Papa John's International, Inc.",
                             'ticker': 'PZZA'},
                            {'currency': 'USD',
                             'name': 'Norwegian Cruise Line Holdings ',
                             'ticker': 'NCLH'},
                            {'currency': 'USD',
                             'name': "McDonald's Corporation",
                             'ticker': 'MCD'},
                            {'currency': 'USD',
                             'name': 'TAL Education Group',
                             'ticker': 'TAL'},
                            {'currency': 'USD',
                             'name': 'Planet Fitness, Inc.',
                             'ticker': 'PLNT'},
                            {'currency': 'USD',
                             'name': 'Ulta Beauty, Inc.',
                             'ticker': 'ULTA'},
                            {'currency': 'USD',
                             'name': 'V.F. Corporation',
                             'ticker': 'VFC'},
                            {'currency': 'USD',
                             'name': 'Stitch Fix, Inc.',
                             'ticker': 'SFIX'},
                            {'currency': 'USD',
                             'name': 'Urban Outfitters, Inc.',
                             'ticker': 'URBN'},
                            {'currency': 'USD',
                             'name': 'Vera Bradley, Inc.',
                             'ticker': 'VRA'},
                            {'currency': 'USD',
                             'name': 'Wyndham Destinations, Inc.',
                             'ticker': 'WYND'},
                            {'currency': 'USD',
                             'name': 'Lyft, Inc.',
                             'ticker': 'LYFT'},
                            {'currency': 'USD',
                             'name': 'Walt Disney Company (The)',
                             'ticker': 'DIS'},
                            {'currency': 'USD',
                             'name': 'Boyd Gaming Corporation',
                             'ticker': 'BYD'},
                            {'currency': 'USD',
                             'name': 'Tiffany & Co.',
                             'ticker': 'TIF'},
                            {'currency': 'USD',
                             'name': 'Daily Journal Corp. (S.C.)',
                             'ticker': 'DJCO'},
                            {'currency': 'USD',
                             'name': 'Foot Locker, Inc.',
                             'ticker': 'FL'},
                            {'currency': 'USD',
                             'name': 'Barnes & Noble Education, Inc',
                             'ticker': 'BNED'},
                            {'currency': 'USD',
                             'name': 'Movado Group Inc.',
                             'ticker': 'MOV'},
                            {'currency': 'USD',
                             'name': 'Starbucks Corporation',
                             'ticker': 'SBUX'},
                            {'currency': 'USD',
                             'name': 'TJX Companies, Inc. (The)',
                             'ticker': 'TJX'},
                            {'currency': 'USD',
                             'name': 'Canada Goose Holdings Inc. Subo',
                             'ticker': 'GOOS'},
                            {'currency': 'USD',
                             'name': 'Uber Technologies, Inc.',
                             'ticker': 'UBER'}],
 'Consumer Staples': [{'currency': 'USD',
                       'name': 'Monster Beverage Corporation',
                       'ticker': 'MNST'},
                      {'currency': 'USD',
                       'name': 'McKesson Corporation',
                       'ticker': 'MCK'},
                      {'currency': 'INR',
                       'name': 'GODREJ CONSUMER PRODUCTS LTD.',
                       'ticker': 'GODREJCP.BO'},
                      {'currency': 'USD',
                       'name': 'Molson Coors Beverage Company',
                       'ticker': 'TAP'},
                      {'currency': 'USD',
                       'name': 'Rite Aid Corporation',
                       'ticker': 'RAD'},
                      {'currency': 'BRL',
                       'name': 'GRUPO NATURAON      NM',
                       'ticker': 'NTCO3.SA'},
                      {'currency': 'USD',
                       'name': 'RECKITT BENCKISER GROUP PLC',
                       'ticker': 'RBGLY'},
                      {'currency': 'GBp',
                       'name': 'SAINSBURY (J) PLC ORD 28 4/7P',
                       'ticker': 'SBRY.L'},
                      {'currency': 'USD',
                       'name': 'Unilever PLC',
                       'ticker': 'UL'},
                      {'currency': 'CNY',
                       'name': 'KWEICHOW MOUTAI',
                       'ticker': '600519.SS'},
                      {'currency': 'CAD',
                       'name': 'ZENABIS GLOBAL INC',
                       'ticker': 'ZENA.TO'},
                      {'currency': 'GBp',
                       'name': 'WYNNSTAY GROUP PLC ORD 25P',
                       'ticker': 'WYN.L'},
                      {'currency': 'GBp',
                       'name': 'UNILEVER PLC ORD 3 1/9P',
                       'ticker': 'ULVR.L'},
                      {'currency': 'CNY',
                       'name': 'WULIANGYE YIBIN CO',
                       'ticker': '000858.SZ'},
                      {'currency': 'BRL',
                       'name': 'CARREFOUR BRON      NM',
                       'ticker': 'CRFB3.SA'},
##                      {'currency': 'USD',
##                       'name': 'Error',
##                       'ticker': 'PCAR4.SA'},
                      {'currency': 'INR',
                       'name': 'Godrej Agrovet Limited',
                       'ticker': 'GODREJAGRO.BO'},
                      {'currency': 'INR',
                       'name': 'NESTLE INDIA LTD.',
                       'ticker': 'NESTLEIND.BO'},
                      {'currency': 'BRL',
                       'name': 'RAIADROGASILON      NM',
                       'ticker': 'RADL3.SA'},
                      {'currency': 'USD',
                       'name': 'Coca-Cola Company (The)',
                       'ticker': 'KO'},
                      {'currency': 'BRL',
                       'name': 'AMBEV S/A   ON',
                       'ticker': 'ABEV3.SA'},
                      {'currency': 'INR',
                       'name': 'HINDUSTAN UNILEVER LTD.',
                       'ticker': 'HINDUNILVR.BO'},
                      {'currency': 'BRL',
                       'name': 'BRF SA      ON      NM',
                       'ticker': 'BRFS3.SA'},
                      {'currency': 'INR',
                       'name': 'ITC LTD.',
                       'ticker': 'ITC.BO'},
                      {'currency': 'CAD',
                       'name': 'ALIMENTATION COUCHE-TARD INC CL',
                       'ticker': 'ATD-B.TO'},
                      {'currency': 'BRL',
                       'name': 'JBS         ON      NM',
                       'ticker': 'JBSS3.SA'},
                      {'currency': 'USD',
                       'name': 'CVS Health Corporation',
                       'ticker': 'CVS'},
                      {'currency': 'BRL',
                       'name': 'M.DIASBRANCOON      NM',
                       'ticker': 'MDIA3.SA'},
                      {'currency': 'USD',
                       'name': 'Treehouse Foods, Inc.',
                       'ticker': 'THS'},
                      {'currency': 'USD',
                       'name': 'Kellogg Company',
                       'ticker': 'K'},
                      {'currency': 'USD',
                       'name': 'McCormick & Company, Incorporat',
                       'ticker': 'MKC'},
                      {'currency': 'USD',
                       'name': 'Tyson Foods, Inc.',
                       'ticker': 'TSN'},
                      {'currency': 'USD',
                       'name': 'Sysco Corporation',
                       'ticker': 'SYY'},
                      {'currency': 'USD',
                       'name': 'J & J Snack Foods Corp.',
                       'ticker': 'JJSF'},
                      {'currency': 'USD',
                       'name': 'The Hershey Company',
                       'ticker': 'HSY'},
                      {'currency': 'USD',
                       'name': 'General Mills, Inc.',
                       'ticker': 'GIS'},
                      {'currency': 'USD',
                       'name': 'National Beverage Corp.',
                       'ticker': 'FIZZ'},
                      {'currency': 'USD',
                       'name': 'Five Below, Inc.',
                       'ticker': 'FIVE'},
                      {'currency': 'USD',
                       'name': 'Tootsie Roll Industries, Inc.',
                       'ticker': 'TR'},
                      {'currency': 'USD',
                       'name': 'Pepsico, Inc.',
                       'ticker': 'PEP'},
                      {'currency': 'USD',
                       'name': 'Colgate-Palmolive Company',
                       'ticker': 'CL'},
                      {'currency': 'USD',
                       'name': 'WD-40 Company',
                       'ticker': 'WDFC'},
                      {'currency': 'USD',
                       'name': 'Procter & Gamble Company (The)',
                       'ticker': 'PG'},
                      {'currency': 'USD',
                       'name': 'Sprouts Farmers Market, Inc.',
                       'ticker': 'SFM'},
                      {'currency': 'USD',
                       'name': 'United Natural Foods, Inc.',
                       'ticker': 'UNFI'},
                      {'currency': 'USD',
                       'name': 'Campbell Soup Company',
                       'ticker': 'CPB'},
                      {'currency': 'USD',
                       'name': 'Keurig Dr Pepper Inc.',
                       'ticker': 'KDP'},
                      {'currency': 'USD',
                       'name': 'Caseys General Stores, Inc.',
                       'ticker': 'CASY'},
                      {'currency': 'USD',
                       'name': 'Corteva, Inc.',
                       'ticker': 'CTVA'}],
 'Energy': [{'currency': 'GBp',
             'name': 'TULLOW OIL PLC ORD 10P',
             'ticker': 'TLW.L'},
            {'currency': 'USD', 'name': 'CNOOC Limited', 'ticker': 'CEO'},
            {'currency': 'USD', 'name': 'Energy Transfer LP', 'ticker': 'ET'},
            {'currency': 'USD', 'name': 'Aemetis, Inc', 'ticker': 'AMTX'},
            {'currency': 'USD',
             'name': 'China Petroleum & Chemical Corp',
             'ticker': 'SNP'},
            {'currency': 'USD', 'name': 'Chevron Corporation', 'ticker': 'CVX'},
            {'currency': 'USD',
             'name': 'Canadian Natural Resources Limi',
             'ticker': 'CNQ'},
            {'currency': 'BRL',
             'name': 'PETROBRAS   ON      N2',
             'ticker': 'PETR3.SA'},
            {'currency': 'USD',
             'name': 'Exxon Mobil Corporation',
             'ticker': 'XOM'},
            {'currency': 'BRL',
             'name': 'PETROBRAS BRON      NM',
             'ticker': 'BRDT3.SA'},
            {'currency': 'HKD', 'name': 'PETROCHINA', 'ticker': '0857.HK'},
            {'currency': 'USD', 'name': 'Hess Corporation', 'ticker': 'HES'},
            {'currency': 'USD', 'name': 'Cameco Corporation', 'ticker': 'CCJ'},
            {'currency': 'USD',
             'name': 'Ultrapar Participacoes S.A. (Ne',
             'ticker': 'UGP'},
            {'currency': 'USD',
             'name': 'Natural Gas Services Group, Inc',
             'ticker': 'NGS'},
            {'currency': 'USD',
             'name': 'National Oilwell Varco, Inc.',
             'ticker': 'NOV'},
            {'currency': 'HKD', 'name': 'SINOPEC CORP', 'ticker': '0386.HK'},
            {'currency': 'GBp',
             'name': 'GLENCORE PLC ORD USD0.01',
             'ticker': 'GLEN.L'},
            {'currency': 'USD',
             'name': 'Torchlight Energy Resources, In',
             'ticker': 'TRCH'},
            {'currency': 'INR',
             'name': 'OIL & NATURAL GAS',
             'ticker': 'ONGC.NS'},
            {'currency': 'INR', 'name': 'SJVN LTD', 'ticker': 'SJVN.BO'},
            {'currency': 'INR',
             'name': 'COAL INDIA LTD.',
             'ticker': 'COALINDIA.BO'},
            {'currency': 'USD',
             'name': 'LAM RESEARCH CORP LAM RESEARCH ',
             'ticker': '0JT5.L'},
            {'currency': 'INR',
             'name': 'RELIANCE INDS',
             'ticker': 'RELIANCE.NS'},
            {'currency': 'USD', 'name': 'Suncor Energy  Inc.', 'ticker': 'SU'},
            {'currency': 'USD', 'name': 'ONEOK, Inc.', 'ticker': 'OKE'},
            {'currency': 'USD',
             'name': 'PetroChina Company Limited',
             'ticker': 'PTR'},
            {'currency': 'USD', 'name': 'Sunoco LP', 'ticker': 'SUN'},
            {'currency': 'BRL',
             'name': 'COSAN       ON      NM',
             'ticker': 'CSAN3.SA'},
            {'currency': 'GBp',
             'name': "ROYAL DUTCH SHELL PLC 'A' ORD E",
             'ticker': 'RDSA.L'},
            {'currency': 'USD',
             'name': 'Continental Resources, Inc.',
             'ticker': 'CLR'},
            {'currency': 'BRL',
             'name': 'PETROBRAS   PN      N2',
             'ticker': 'PETR4.SA'},
            {'currency': 'USD', 'name': 'BP p.l.c.', 'ticker': 'BP'},
            {'currency': 'USD', 'name': 'Phillips 66', 'ticker': 'PSX'}],
 'Financial Services': [{'currency': 'USD',
                         'name': 'China Finance Online Co. Limite',
                         'ticker': 'JRJC'},
                        {'currency': 'USD',
                         'name': 'Bank OZK',
                         'ticker': 'OZK'},
                        {'currency': 'BRL',
                         'name': 'ITAUUNIBANCOPN  ED  N1',
                         'ticker': 'ITUB4.SA'},
                        {'currency': 'USD',
                         'name': "Moody's Corporation",
                         'ticker': 'MCO'},
                        {'currency': 'USD',
                         'name': 'Oppenheimer Holdings, Inc.',
                         'ticker': 'OPY'},
                        {'currency': 'USD',
                         'name': 'Glacier Bancorp, Inc.',
                         'ticker': 'GBCI'},
                        {'currency': 'USD',
                         'name': 'Meritage Homes Corporation',
                         'ticker': 'MTh'},
                        {'currency': 'USD',
                         'name': 'JP Morgan Chase & Co.',
                         'ticker': 'JPM'},
                        {'currency': 'USD',
                         'name': 'SuRo Capital Corp.',
                         'ticker': 'SSSS'},
                        {'currency': 'BRL',
                         'name': 'ITAUSA      PN      N1',
                         'ticker': 'ITSA4.SA'},
                        {'currency': 'INR',
                         'name': 'KOTAK MAHINDRA BANK LTD.',
                         'ticker': 'KOTAKBANK.BO'},
                        {'currency': 'BRL',
                         'name': 'B3          ON      NM',
                         'ticker': 'B3SA3.SA'},
                        {'currency': 'BRL',
                         'name': 'BTGP BANCO  UNT     N2',
                         'ticker': 'BPAC11.SA'},
                        {'currency': 'USD',
                         'name': 'Geo Group Inc (The) REIT',
                         'ticker': 'GEO'},
                        {'currency': 'USD',
                         'name': 'Wells Fargo & Company',
                         'ticker': 'WFC'},
                        {'currency': 'INR',
                         'name': 'STATE BANK OF INDIA',
                         'ticker': 'SBIN.BO'},
                        {'currency': 'INR',
                         'name': 'HOUSING DEVELOPMENT FINANCE CO',
                         'ticker': 'HDFC.BO'},
                        {'currency': 'INR',
                         'name': 'REC LIMITED',
                         'ticker': '532955.BO'},
                        {'currency': 'USD',
                         'name': 'Citigroup, Inc.',
                         'ticker': 'C'},
                        {'currency': 'INR',
                         'name': 'ICICI BANK LTD.',
                         'ticker': 'ICICIBANK.BO'},
                        {'currency': 'BRL',
                         'name': 'MULTIPLAN   ON      N2',
                         'ticker': 'MULT3.SA'},
                        {'currency': 'INR',
                         'name': 'HDFC BANK LTD.',
                         'ticker': 'HDFCBANK.BO'},
##                        {'currency': 'USD',
##                         'name': 'Error',
##                         'ticker': '532215.BO'},
                        {'currency': 'CNY',
                         'name': 'CHINA WORLD TRADE CENTER',
                         'ticker': '600007.SS'},
                        {'currency': 'INR',
                         'name': 'Max Financial Services Limited',
                         'ticker': 'MFSL.BO'},
                        {'currency': 'USD',
                         'name': 'Fair Isaac Corproation',
                         'ticker': 'FICO'},
                        {'currency': 'BRL',
                         'name': 'SANTANDER BRUNT',
                         'ticker': 'SANB11.SA'},
                        {'currency': 'USD',
                         'name': 'Barclays PLC',
                         'ticker': 'BCS'},
                        {'currency': 'GBp',
                         'name': 'HSBC HOLDINGS PLC ORD $0.50 (UK',
                         'ticker': 'HSBA.L'},
                        {'currency': 'BRL',
                         'name': 'BRASIL      ON      NM',
                         'ticker': 'BBAS3.SA'},
                        {'currency': 'CAD',
                         'name': 'GREAT-WEST LIFECO INC',
                         'ticker': 'GWO.TO'},
                        {'currency': 'BRL',
                         'name': 'PORTO SEGUROON      NM',
                         'ticker': 'PSSA3.SA'},
                        {'currency': 'CAD',
                         'name': 'CDN WESTERN BANK',
                         'ticker': 'CWB.TO'},
                        {'currency': 'GBp',
                         'name': 'STANDARD CHARTERED PLC ORD USD0',
                         'ticker': 'STAN.L'},
                        {'currency': 'CNY',
                         'name': 'BANK OF NINGBO CO.',
                         'ticker': '002142.SZ'},
                        {'currency': 'HKD', 'name': 'CCB', 'ticker': '0939.HK'},
                        {'currency': 'GBp',
                         'name': 'AVIVA PLC ORD 25P',
                         'ticker': 'AV.L'},
                        {'currency': 'CNY',
                         'name': 'CHINA VANKE CO',
                         'ticker': '000002.SZ'},
                        {'currency': 'BRL',
                         'name': 'BR MALLS PARON      NM',
                         'ticker': 'BRML3.SA'},
                        {'currency': 'HKD',
                         'name': 'PING AN',
                         'ticker': '2318.HK'},
                        {'currency': 'BRL',
                         'name': 'BBSEGURIDADEON      NM',
                         'ticker': 'BBSE3.SA'},
                        {'currency': 'BRL',
                         'name': 'IRBBRASIL REON      NM',
                         'ticker': 'IRBR3.SA'},
                        {'currency': 'BRL',
                         'name': 'BRADESCO    ON  EJ  N1',
                         'ticker': 'BBDC3.SA'},
##                        {'currency': 'USD',
##                         'name': 'Error',
##                         'ticker': 'YESBANK.BO'},
                        {'currency': 'HKD',
                         'name': 'CHINA VANKE',
                         'ticker': '2202.HK'},
                        {'currency': 'BRL',
                         'name': 'SUL AMERICA UNT     N2',
                         'ticker': 'SULA11.SA'},
                        {'currency': 'GBp',
                         'name': '1062598',
                         'ticker': 'SDR.L'},
                        {'currency': 'CAD',
                         'name': 'FAIRFAX FINANCIAL HOLDINGS LTD.',
                         'ticker': 'FFH.TO'},
                        {'currency': 'USD',
                         'name': 'The Blackstone Group Inc.',
                         'ticker': 'BX'},
                        {'currency': 'GBp',
                         'name': 'EXPERIAN PLC ORD USD0.10',
                         'ticker': 'EXPN.L'},
                        {'currency': 'GBp',
                         'name': 'LLOYDS BANKING GROUP PLC ORD 10',
                         'ticker': 'LLOY.L'},
                        {'currency': 'BRL',
                         'name': 'BRADESCO    PN  EJ  N1',
                         'ticker': 'BBDC4.SA'},
                        {'currency': 'GBp',
                         'name': 'CITY OF LONDON INVESTMENT GROUP',
                         'ticker': 'CLIG.L'},
                        {'currency': 'USD',
                         'name': 'PNC Financial Services Group, I',
                         'ticker': 'PNC'},
                        {'currency': 'INR',
                         'name': 'BAJAJ FINSERV LTD.',
                         'ticker': 'BAJAJFINSV.BO'},
                        {'currency': 'USD',
                         'name': 'Extra Space Storage Inc',
                         'ticker': 'EXR'},
                        {'currency': 'USD',
                         'name': 'Westpac Banking Corporation',
                         'ticker': 'WBK'},
                        {'currency': 'BRL',
                         'name': 'CIELO       ON      NM',
                         'ticker': 'CIEL3.SA'},
                        {'currency': 'USD',
                         'name': 'Allstate Corporation (The)',
                         'ticker': 'ALL'},
                        {'currency': 'USD',
                         'name': 'Deutsche Bank AG',
                         'ticker': 'DB'},
                        {'currency': 'USD',
                         'name': 'Lazard LTD. Lazard, LTD.',
                         'ticker': 'LAZ'},
                        {'currency': 'USD',
                         'name': 'Loews Corporation',
                         'ticker': 'L'},
                        {'currency': 'USD',
                         'name': 'Artisan Partners Asset Manageme',
                         'ticker': 'APAM'},
                        {'currency': 'USD',
                         'name': 'AFLAC Incorporated',
                         'ticker': 'AFL'},
                        {'currency': 'USD',
                         'name': 'American Express Company',
                         'ticker': 'AXP'},
                        {'currency': 'USD',
                         'name': 'Physicians Realty Trust',
                         'ticker': 'DOC'},
                        {'currency': 'USD', 'name': 'KeyCorp', 'ticker': 'KEY'},
                        {'currency': 'USD',
                         'name': 'Mastercard Incorporated',
                         'ticker': 'MA'},
                        {'currency': 'USD',
                         'name': 'Discover Financial Services',
                         'ticker': 'DFS'},
                        {'currency': 'USD',
                         'name': 'Old National Bancorp',
                         'ticker': 'ONB'},
                        {'currency': 'USD',
                         'name': 'NatWest Group plc',
                         'ticker': 'NWG'},
                        {'currency': 'USD',
                         'name': 'Great Elm Capital Group, Inc.',
                         'ticker': 'GEC'},
                        {'currency': 'USD',
                         'name': 'Bank Nova Scotia Halifax Pfd 3',
                         'ticker': 'BNS'},
                        {'currency': 'USD',
                         'name': 'Prudential Financial, Inc.',
                         'ticker': 'PRU'},
                        {'currency': 'USD',
                         'name': 'UBS Group AG Registered',
                         'ticker': 'UBS'},
                        {'currency': 'USD',
                         'name': 'SEI Investments Company',
                         'ticker': 'SEIC'},
                        {'currency': 'USD',
                         'name': 'Mr. Cooper Group Inc.',
                         'ticker': 'COOP'},
                        {'currency': 'USD', 'name': 'Visa Inc.', 'ticker': 'V'},
                        {'currency': 'USD',
                         'name': 'Intercontinental Exchange Inc.',
                         'ticker': 'ICE'},
                        {'currency': 'USD',
                         'name': 'Iron Mountain Incorporated (Del',
                         'ticker': 'IRM'},
                        {'currency': 'USD',
                         'name': 'Credit Suisse Group',
                         'ticker': 'CS'},
                        {'currency': 'USD',
                         'name': 'Digital Realty Trust, Inc.',
                         'ticker': 'DLR'},
                        {'currency': 'USD',
                         'name': 'Legg Mason, Inc.',
                         'ticker': 'LM'},
                        {'currency': 'USD',
                         'name': 'KKR & Co. Inc.',
                         'ticker': 'KKR'},
                        {'currency': 'USD',
                         'name': 'Regions Financial Corporation',
                         'ticker': 'RF'},
                        {'currency': 'USD',
                         'name': 'PayPal Holdings, Inc.',
                         'ticker': 'PYPL'},
                        {'currency': 'USD',
                         'name': 'MetLife, Inc.',
                         'ticker': 'MET'},
                        {'currency': 'USD',
                         'name': 'Boston Private Financial Holdin',
                         'ticker': 'BPFH'},
                        {'currency': 'USD',
                         'name': 'Public Storage',
                         'ticker': 'PSA'}],
 'Healthcare': [{'currency': 'USD',
                 'name': 'Bristol-Myers Squibb Company',
                 'ticker': 'BMY'},
                {'currency': 'USD',
                 'name': 'Aurora Cannabis Inc.',
                 'ticker': 'ACB'},
                {'currency': 'USD',
                 'name': 'Merck & Company, Inc.',
                 'ticker': 'MRK'},
                {'currency': 'USD',
                 'name': 'Tivity Health, Inc.',
                 'ticker': 'TVTY'},
                {'currency': 'INR',
                 'name': 'PIRAMAL ENTERPRISES LTD.',
                 'ticker': 'PEL.BO'},
                {'currency': 'USD',
                 'name': 'Cardiovascular Systems, Inc.',
                 'ticker': 'CSII'},
                {'currency': 'INR',
                 'name': 'SUN PHARMACEUTICAL INDUSTRIES',
                 'ticker': 'SUNPHARMA.BO'},
                {'currency': 'CNY',
                 'name': 'SHENZHEN MINDRAY B',
                 'ticker': '300760.SZ'},
                {'currency': 'USD',
                 'name': 'Cancer Genetics, Inc.',
                 'ticker': 'CGIX'},
                {'currency': 'USD', 'name': 'Zogenix, Inc.', 'ticker': 'ZGNX'},
                {'currency': 'USD',
                 'name': 'Globus Medical, Inc.',
                 'ticker': 'GMED'},
                {'currency': 'USD',
                 'name': 'Takeda Pharmaceutical Company L',
                 'ticker': 'TAK'},
                {'currency': 'INR',
                 'name': 'GRANULES INDIA LTD.',
                 'ticker': 'GRANULES.BO'},
                {'currency': 'USD',
                 'name': 'GlaxoSmithKline PLC',
                 'ticker': 'GSK'},
                {'currency': 'USD', 'name': 'Astrazeneca PLC', 'ticker': 'AZN'},
                {'currency': 'USD',
                 'name': 'UnitedHealth Group Incorporated',
                 'ticker': 'UNH'},
                {'currency': 'USD', 'name': 'AbbVie Inc.', 'ticker': 'ABBV'},
                {'currency': 'USD',
                 'name': 'Bristol-Myers Squibb Company',
                 'ticker': 'BMY'},
                {'currency': 'CNY',
                 'name': 'JIANGSU HENGRUI MEDICAL CO LTD',
                 'ticker': '600276.SS'},
                {'currency': 'BRL',
                 'name': 'HYPERA      ON      NM',
                 'ticker': 'HYPE3.SA'},
                {'currency': 'BRL',
                 'name': 'INTERMEDICA ON      NM',
                 'ticker': 'GNDI3.SA'},
                {'currency': 'USD',
                 'name': 'Acadia Healthcare Company, Inc.',
                 'ticker': 'ACHC'},
                {'currency': 'USD',
                 'name': 'Baxter International Inc.',
                 'ticker': 'BAX'},
                {'currency': 'USD',
                 'name': 'AMN Healthcare Services Inc AMN',
                 'ticker': 'AMN'},
                {'currency': 'USD',
                 'name': 'Regeneron Pharmaceuticals, Inc.',
                 'ticker': 'REGN'},
                {'currency': 'USD', 'name': 'Amgen Inc.', 'ticker': 'AMGN'},
                {'currency': 'USD',
                 'name': 'Teva Pharmaceutical Industries ',
                 'ticker': 'TEVA'},
                {'currency': 'USD',
                 'name': 'Gilead Sciences, Inc.',
                 'ticker': 'GILD'},
                {'currency': 'USD', 'name': 'Pfizer, Inc.', 'ticker': 'PFE'},
                {'currency': 'INR',
                 'name': 'DR.REDDYS LABORATORIES LTD.',
                 'ticker': 'DRREDDY.BO'},
                {'currency': 'INR',
                 'name': 'AUROBINDO PHARMA LTD.',
                 'ticker': 'AUROPHARMA.BO'},
                {'currency': 'USD',
                 'name': 'Johnson & Johnson',
                 'ticker': 'JNJ'},
                {'currency': 'GBp',
                 'name': 'SMITH & NEPHEW PLC ORD USD0.20',
                 'ticker': 'SN.L'},
                # {'currency': 'USD', 'name': 'Error', 'ticker': '500087.BO'},
                {'currency': 'USD',
                 'name': 'Prestige Consumer Healthcare In',
                 'ticker': 'PBH'},
                {'currency': 'USD', 'name': 'Illumina, Inc.', 'ticker': 'ILMN'},
                {'currency': 'USD',
                 'name': 'Catalyst Pharmaceuticals, Inc.',
                 'ticker': 'CPRX'},
                {'currency': 'USD',
                 'name': 'Harvard Bioscience, Inc.',
                 'ticker': 'HBIO'},
                {'currency': 'USD',
                 'name': 'Centene Corporation',
                 'ticker': 'CNC'},
                {'currency': 'USD',
                 'name': 'Myriad Genetics, Inc.',
                 'ticker': 'MYGN'},
                {'currency': 'USD',
                 'name': 'M.D.C. Holdings, Inc.',
                 'ticker': 'MDC'},
                {'currency': 'USD',
                 'name': 'Endo International plc',
                 'ticker': 'ENDP'},
                {'currency': 'USD', 'name': 'Novartis AG', 'ticker': 'NVS'}],
 'Materials & Processing': [{'currency': 'USD',
                             'name': 'Northern Technologies Internati',
                             'ticker': 'NTIC'},
                            {'currency': 'USD',
                             'name': 'Rio Tinto Plc',
                             'ticker': 'RIO'},
                            {'currency': 'USD',
                             'name': 'Fuwei Films (Holdings) Co., Ltd',
                             'ticker': 'FFHL'},
                            {'currency': 'USD',
                             'name': 'Rio Tinto Plc',
                             'ticker': 'RIO'},
                            {'currency': 'INR',
                             'name': 'ASIAN PAINTS LTD.',
                             'ticker': 'ASIANPAINT.BO'},
                            {'currency': 'USD',
                             'name': 'United States Steel Corporation',
                             'ticker': 'X'},
                            {'currency': 'GBp',
                             'name': 'MELODYVR GROUP PLC ORD GBP0.01',
                             'ticker': 'MVR.L'},
                            {'currency': 'USD',
                             'name': 'AK Steel Holding Corporation',
                             'ticker': 'AKS'},
                            {'currency': 'GBp',
                             'name': 'FERGUSON PLC ORD 10P',
                             'ticker': 'FERG.L'},
                            {'currency': 'INR',
                             'name': 'BERGER PAINTS INDIA LTD.',
                             'ticker': 'BERGEPAINT.BO'},
                            {'currency': 'USD',
                             'name': 'FMC Corporation',
                             'ticker': 'FMC'},
                            {'currency': 'GBp',
                             'name': 'MONDI PLC ORD EUR 0.20',
                             'ticker': 'MNDI.L'},
                            {'currency': 'USD',
                             'name': 'Aluminum Corporation of China L',
                             'ticker': 'ACH'},
                            {'currency': 'HKD',
                             'name': 'CONCH CEMENT',
                             'ticker': '0914.HK'},
                            {'currency': 'BRL',
                             'name': 'VALE        ON      NM',
                             'ticker': 'VALE3.SA'},
                            {'currency': 'GBp',
                             'name': 'JOHNSON MATTHEY PLC ORD 110 49/',
                             'ticker': 'JMAT.L'},
                            {'currency': 'BRL',
                             'name': 'GERDAU      PN      N1',
                             'ticker': 'GGBR4.SA'},
                            {'currency': 'USD',
                             'name': 'China Natural Resources, Inc.',
                             'ticker': 'CHNR'},
                            {'currency': 'USD',
                             'name': 'Ashland Global Holdings Inc.',
                             'ticker': 'ASH'},
                            {'currency': 'BRL',
                             'name': 'KLABIN S/A  UNT     N2',
                             'ticker': 'KLBN11.SA'},
                            {'currency': 'BRL',
                             'name': 'SID NACIONALON',
                             'ticker': 'CSNA3.SA'},
                            {'currency': 'USD',
                             'name': 'BHP Group Limited',
                             'ticker': 'BHP'},
                            {'currency': 'USD',
                             'name': 'Beacon Roofing Supply, Inc.',
                             'ticker': 'BECN'},
                            {'currency': 'USD',
                             'name': 'Neenah, Inc.',
                             'ticker': 'NP'},
                            {'currency': 'BRL',
                             'name': 'BRASKEM     PNA     N1',
                             'ticker': 'BRKM5.SA'},
                            {'currency': 'INR',
                             'name': 'VEDANTA LIMITED',
                             'ticker': 'VEDL.BO'},
                            {'currency': 'INR',
                             'name': 'ULTRATECH CEMENT LTD.',
                             'ticker': 'ULTRACEMCO.BO'},
                            {'currency': 'INR',
                             'name': 'TATA STEEL LTD.',
                             'ticker': 'TATASTEEL.BO'},
                            {'currency': 'INR',
                             'name': 'HINDALCO INDUSTRIES LTD.',
                             'ticker': 'HINDALCO.BO'},
                            {'currency': 'USD',
                             'name': 'Gibraltar Industries, Inc.',
                             'ticker': 'ROCK'},
                            {'currency': 'CNY',
                             'name': 'ANHUI CONCH CEMENT',
                             'ticker': '600585.SS'},
                            {'currency': 'USD',
                             'name': 'Royal Gold, Inc.',
                             'ticker': 'RGLD'},
                            {'currency': 'USD',
                             'name': 'Kirkland Lake Gold Ltd.',
                             'ticker': 'KL'},
                            {'currency': 'USD',
                             'name': 'Freeport-McMoRan, Inc.',
                             'ticker': 'FCX'},
                            {'currency': 'USD',
                             'name': 'Air Products and Chemicals, Inc',
                             'ticker': 'APD'},
                            {'currency': 'USD',
                             'name': 'Clearwater Paper Corporation',
                             'ticker': 'CLW'},
                            {'currency': 'BRL',
                             'name': 'SUZANO S.A. ON      NM',
                             'ticker': 'SUZB3.SA'},
                            {'currency': 'USD',
                             'name': 'Eastman Chemical Company',
                             'ticker': 'EMN'},
                            {'currency': 'USD',
                             'name': 'RBC Bearings Incorporated',
                             'ticker': 'ROLL'},
                            {'currency': 'INR',
                             'name': 'ATUL LTD.',
                             'ticker': 'ATUL.BO'},
                            {'currency': 'USD',
                             'name': 'SSR Mining Inc.',
                             'ticker': 'SSRM'},
                            {'currency': 'USD',
                             'name': 'Avis Budget Group, Inc.',
                             'ticker': 'CAR'},
                            {'currency': 'USD',
                             'name': 'Innospec Inc.',
                             'ticker': 'IOSP'},
                            {'currency': 'USD',
                             'name': 'Quaker Chemical Corporation',
                             'ticker': 'KWR'},
                            {'currency': 'USD',
                             'name': 'Eastman Chemical Company',
                             'ticker': 'EMN'},
                            {'currency': 'USD',
                             'name': 'POSCO',
                             'ticker': 'PKX'},
                            {'currency': 'USD',
                             'name': 'Kaiser Aluminum Corporation',
                             'ticker': 'KALU'}],
 'Producer Durables': [{'currency': 'CAD',
                        'name': 'CARGOJET INC.',
                        'ticker': 'CJT.TO'},
                       {'currency': 'USD',
                        'name': 'Kansas City Southern',
                        'ticker': 'KSU'},
                       {'currency': 'CAD',
                        'name': 'AIR CANADA',
                        'ticker': 'AC.TO'},
                       {'currency': 'USD',
                        'name': 'Guangshen Railway Company Limit',
                        'ticker': 'GSH'},
                       {'currency': 'HKD',
                        'name': 'CHINA STATE CON',
                        'ticker': '3311.HK'},
                       {'currency': 'USD',
                        'name': 'China Southern Airlines Company',
                        'ticker': 'ZNH'},
                       {'currency': 'INR',
                        'name': 'LARSEN & TOUBRO LTD.',
                        'ticker': 'LT.BO'},
                       {'currency': 'GBp',
                        'name': 'EASYJET PLC ORD 27 2/7P',
                        'ticker': 'EZJ.L'},
                       {'currency': 'GBp',
                        'name': 'SMITHS GROUP PLC ORD 37.5P',
                        'ticker': 'SMIN.L'},
                       {'currency': 'BRL',
                        'name': 'EMBRAER     ON      NM',
                        'ticker': 'EMBR3.SA'},
                       {'currency': 'CAD',
                        'name': 'BOMBARDIER INC., CL. B, SV',
                        'ticker': 'BBD-B.TO'},
                       {'currency': 'BRL',
                        'name': 'CCR SA      ON      NM',
                        'ticker': 'CCRO3.SA'},
                       {'currency': 'USD',
                        'name': 'Lockheed Martin Corporation',
                        'ticker': 'LMT'},
                       {'currency': 'USD',
                        'name': 'ArcBest Corporation',
                        'ticker': 'ARCB'},
                       {'currency': 'GBp',
                        'name': 'BUNZL PLC ORD 32 1/7P',
                        'ticker': 'BNZL.L'},
                       {'currency': 'USD',
                        'name': 'ZTO Express (Cayman) Inc.',
                        'ticker': 'ZTO'},
                       {'currency': 'USD',
                        'name': 'ASGN Incorporated',
                        'ticker': 'ASGN'},
                       {'currency': 'USD',
                        'name': 'China Yuchai International Limi',
                        'ticker': 'CYD'},
                       {'currency': 'USD',
                        'name': 'Ashland Global Holdings Inc.',
                        'ticker': 'ASH'},
                       {'currency': 'CNY',
                        'name': 'SHANGHAI INTERNATIONAL AIRPORT ',
                        'ticker': '600009.SS'},
                       {'currency': 'USD',
                        'name': 'Boeing Company (The)',
                        'ticker': 'BA'},
                       {'currency': 'BRL',
                        'name': 'WEG         ON      NM',
                        'ticker': 'WEGE3.SA'},
                       {'currency': 'USD',
                        'name': 'SkyWest, Inc.',
                        'ticker': 'SKYW'},
                       {'currency': 'USD',
                        'name': 'PACCAR Inc.',
                        'ticker': 'PCAR'},
                       {'currency': 'USD',
                        'name': 'Douglas Dynamics, Inc.',
                        'ticker': 'PLOW'},
                       {'currency': 'BRL',
                        'name': 'RUMO S.A.   ON      NM',
                        'ticker': 'RAIL3.SA'},
                       {'currency': 'GBp',
                        'name': 'ROLLS-ROYCE HOLDINGS PLC ORD SH',
                        'ticker': 'RR.L'},
                       {'currency': 'HKD',
                        'name': 'CITIC',
                        'ticker': '0267.HK'},
                       {'currency': 'USD',
                        'name': 'Heartland Express, Inc.',
                        'ticker': 'HTLD'},
                       {'currency': 'USD',
                        'name': 'Wabash National Corporation',
                        'ticker': 'WNC'},
                       {'currency': 'USD',
                        'name': 'Southwest Airlines Company',
                        'ticker': 'LUV'},
                       {'currency': 'USD',
                        'name': 'JetBlue Airways Corporation',
                        'ticker': 'JBLU'},
                       {'currency': 'USD',
                        'name': 'Snap-On Incorporated',
                        'ticker': 'SNA'},
                       {'currency': 'USD',
                        'name': 'Spirit Airlines, Inc.',
                        'ticker': 'SAVE'},
                       {'currency': 'USD',
                        'name': 'American Airlines Group, Inc.',
                        'ticker': 'AAL'},
                       {'currency': 'USD',
                        'name': 'Verisk Analytics, Inc.',
                        'ticker': 'VRSK'},
                       {'currency': 'USD',
                        'name': 'The Middleby Corporation',
                        'ticker': 'MIDD'},
                       {'currency': 'USD',
                        'name': 'Delta Air Lines, Inc.',
                        'ticker': 'DAL'},
                       {'currency': 'USD',
                        'name': 'The Shyft Group, Inc.',
                        'ticker': 'SHYF'},
                       {'currency': 'USD',
                        'name': 'FTI Consulting, Inc.',
                        'ticker': 'FCN'},
                       {'currency': 'USD',
                        'name': 'China Eastern Airlines Corporat',
                        'ticker': 'CEA'},
                       {'currency': 'USD',
                        'name': 'Titan International, Inc. (DE)',
                        'ticker': 'TWI'},
##                       {'currency': 'USD',
##                        'name': 'Error',
##                        'ticker': '500103.BO'},
##                       {'currency': 'USD',
##                        'name': 'Error',
##                        'ticker': '532927.BO'}
                       ],
 'Technology': [{'currency': 'GBp',
                 'name': 'MICRO FOCUS INTERNATIONAL PLC O',
                 'ticker': 'MCRO.L'},
                {'currency': 'USD',
                 'name': 'UTStarcom Holdings Corp',
                 'ticker': 'UTSI'},
                {'currency': 'USD', 'name': 'Groupon, Inc.', 'ticker': 'GRPN'},
                {'currency': 'USD', 'name': 'Apple Inc.', 'ticker': 'AAPL'},
                {'currency': 'USD',
                 'name': 'The9 Limited - American Deposit',
                 'ticker': 'NCTY'},
                {'currency': 'INR',
                 'name': 'NIIT LTD.',
                 'ticker': 'NIITLTD.BO'},
                {'currency': 'USD',
                 'name': 'Manhattan Associates, Inc.',
                 'ticker': 'MANH'},
                {'currency': 'CNY',
                 'name': 'FOXCONN INDUSTRIAL INTERNET CO ',
                 'ticker': '601138.SS'},
                {'currency': 'INR', 'name': 'WIPRO LTD.', 'ticker': 'WIPRO.BO'},
                {'currency': 'INR',
                 'name': 'INFOSYS LTD.',
                 'ticker': 'INFY.BO'},
                {'currency': 'USD',
                 'name': 'Capital Senior Living Corporati',
                 'ticker': 'CSU'},
                {'currency': 'INR',
                 'name': 'JUST DIAL LTD.',
                 'ticker': 'JUSTDIAL.BO'},
                {'currency': 'GBp',
                 'name': 'DISCOVERIE GROUP PLC ORD 5P',
                 'ticker': 'DSCV.L'},
                {'currency': 'HKD', 'name': 'MEITUAN-W', 'ticker': '3690.HK'},
                {'currency': 'GBp',
                 'name': 'SAGE GROUP PLC ORD 1 4/77P',
                 'ticker': 'SGE.L'},
                {'currency': 'USD', 'name': 'Zynga Inc.', 'ticker': 'ZNGA'},
                {'currency': 'CAD',
                 'name': 'ENGHOUSE SYSTEMS LIMITED',
                 'ticker': 'ENGH.TO'},
                {'currency': 'INR',
                 'name': 'TATA CONSULTANCY SERVICES LTD.',
                 'ticker': 'TCS.BO'},
                {'currency': 'CNY',
                 'name': 'HANGZHOU HIKVISION',
                 'ticker': '002415.SZ'},
                {'currency': 'INR',
                 'name': 'TECH MAHINDRA LTD.',
                 'ticker': 'TECHM.BO'},
                {'currency': 'USD',
                 'name': 'Sina Corporation',
                 'ticker': 'SINA'},
                {'currency': 'INR',
                 'name': 'HCL TECHNOLOGIES LTD.',
                 'ticker': 'HCLTECH.BO'},
                {'currency': 'USD',
                 'name': 'Sohu.com Limited',
                 'ticker': 'SOHU'},
                {'currency': 'INR',
                 'name': 'HEXAWARE TECHNOLOGIES LTD.',
                 'ticker': 'HEXAWARE.BO'},
                {'currency': 'USD', 'name': 'Twitter, Inc.', 'ticker': 'TWTR'},
                {'currency': 'USD', 'name': 'Alphabet Inc.', 'ticker': 'GOOG'},
                {'currency': 'USD',
                 'name': 'NXP Semiconductors N.V.',
                 'ticker': 'NXPI'},
                {'currency': 'USD',
                 'name': 'Arista Networks, Inc.',
                 'ticker': 'ANET'},
                {'currency': 'USD',
                 'name': 'Benefitfocus, Inc.',
                 'ticker': 'BNFT'},
                {'currency': 'USD',
                 'name': 'Cognizant Technology Solutions ',
                 'ticker': 'CTSH'},
                {'currency': 'USD', 'name': 'Adobe Inc.', 'ticker': 'ADBE'},
                {'currency': 'USD',
                 'name': 'Alibaba Group Holding Limited',
                 'ticker': 'BABA'},
                {'currency': 'INR',
                 'name': 'ASTRA MICROWAVE PRODUCTS LTD.',
                 'ticker': 'ASTRAMICRO.BO'},
                {'currency': 'USD',
                 'name': 'Oracle Corporation',
                 'ticker': 'ORCL'},
                {'currency': 'USD', 'name': 'Shopify Inc.', 'ticker': 'SHOP'},
                {'currency': 'USD',
                 'name': 'Slack Technologies, Inc.',
                 'ticker': 'WORK'},
                {'currency': 'INR',
                 'name': 'MINDTREE LTD.',
                 'ticker': 'MINDTREE.BO'},
                {'currency': 'USD', 'name': 'Baidu, Inc.', 'ticker': 'BIDU'},
                {'currency': 'USD', 'name': 'Facebook, Inc.', 'ticker': 'FB'},
                {'currency': 'USD',
                 'name': 'DXC Technology Company',
                 'ticker': 'DXC'},
                {'currency': 'USD',
                 'name': 'Microsoft Corporation',
                 'ticker': 'MSFT'},
                {'currency': 'USD', 'name': 'NetEase, Inc.', 'ticker': 'NTES'},
                {'currency': 'HKD', 'name': 'TENCENT', 'ticker': '0700.HK'}],
 'Utilities': [{'currency': 'USD', 'name': 'BCE, Inc.', 'ticker': 'BCE'},
               {'currency': 'GBp',
                'name': 'BT GROUP PLC ORD 5P',
                'ticker': 'BT-A.L'},
               {'currency': 'USD',
                'name': 'Verizon Communications Inc.',
                'ticker': 'VZ'},
               {'currency': 'USD', 'name': 'Sprint Corporation', 'ticker': 'S'},
               {'currency': 'INR',
                'name': 'MAHANAGAR TELEPHONE NIGAM LTD.',
                'ticker': 'MTNL.BO'},
               {'currency': 'USD',
                'name': 'China Mobile Limited',
                'ticker': 'CHL'},
               {'currency': 'INR',
                'name': 'GUJARAT INDUSTRIES POWER CO.LT',
                'ticker': 'GIPCL.BO'},
               {'currency': 'INR',
                'name': 'GAIL (INDIA) LTD.',
                'ticker': 'GAIL.BO'},
               {'currency': 'INR',
                'name': 'TATA POWER CO.LTD.',
                'ticker': 'TATAPOWER.BO'},
               {'currency': 'USD',
                'name': 'Vodafone Group Plc',
                'ticker': 'VOD'},
               {'currency': 'USD',
                'name': 'China Unicom (Hong Kong) Ltd',
                'ticker': 'CHU'},
               {'currency': 'BRL',
                'name': 'ENERGISA    UNT     N2',
                'ticker': 'ENGI11.SA'},
               {'currency': 'INR', 'name': 'NTPC LTD.', 'ticker': 'NTPC.BO'},
               {'currency': 'CNY',
                'name': 'CHINA YANGTZE POWER CO',
                'ticker': '600900.SS'},
               {'currency': 'CAD',
                'name': 'CANADIAN UTILITIES LTD., CL.A, ',
                'ticker': 'CU.TO'},
               {'currency': 'USD',
                'name': 'Telefonica Brasil, S.A.',
                'ticker': 'VIV'},
               {'currency': 'USD',
                'name': 'Middlesex Water Company',
                'ticker': 'MSEX'},
               {'currency': 'HKD',
                'name': 'CHINA GAS HOLD',
                'ticker': '0384.HK'},
               {'currency': 'GBp',
                'name': 'UNITED UTILITIES GROUP PLC ORD ',
                'ticker': 'UU.L'},
               {'currency': 'BRL',
                'name': 'ELETROBRAS  ON      N1',
                'ticker': 'ELET3.SA'},
               {'currency': 'USD', 'name': 'Gogo Inc.', 'ticker': 'GOGO'},
               {'currency': 'USD', 'name': 'Sempra Energy', 'ticker': 'SRE'},
               {'currency': 'INR',
                'name': 'BHARTI AIRTEL LTD.',
                'ticker': 'BHARTIARTL.BO'},
               {'currency': 'BRL',
                'name': 'CEMIG       PN      N1',
                'ticker': 'CMIG4.SA'},
               {'currency': 'USD',
                'name': 'American Electric Power Company',
                'ticker': 'AEP'},
               {'currency': 'HKD', 'name': 'CHINA MOBILE', 'ticker': '0941.HK'},
               {'currency': 'USD',
                'name': 'China Telecom Corp Ltd',
                'ticker': 'CHA'},
               {'currency': 'USD',
                'name': 'American Water Works Company, I',
                'ticker': 'AWK'},
               {'currency': 'USD',
                'name': 'National Fuel Gas Company',
                'ticker': 'NFG'},
               {'currency': 'BRL',
                'name': 'ENGIE BRASILON      NM',
                'ticker': 'EGIE3.SA'},
               {'currency': 'USD',
                'name': 'Essential Utilities, Inc.',
                'ticker': 'WTRG'},
               {'currency': 'INR',
                'name': 'POWER GRID CORPORATION OF INDI',
                'ticker': 'POWERGRID.BO'},
               {'currency': 'BRL',
                'name': 'EQUATORIAL  ON      NM',
                'ticker': 'EQTL3.SA'},
               {'currency': 'USD',
                'name': 'Southern Company (The)',
                'ticker': 'SO'},
               {'currency': 'USD', 'name': 'SJW Group', 'ticker': 'SJW'},
               {'currency': 'BRL',
                'name': 'ELETROBRAS  PNB     N1',
                'ticker': 'ELET6.SA'},
               {'currency': 'USD', 'name': 'AT&T Inc.', 'ticker': 'T'},
               {'currency': 'BRL',
                'name': 'SABESP      ON      NM',
                'ticker': 'SBSP3.SA'},
               {'currency': 'USD',
                'name': 'Dominion Energy, Inc.',
                'ticker': 'D'},
               # {'currency': 'USD', 'name': 'Error', 'ticker': 'TIMP3.SA'},
               {'currency': 'USD',
                'name': 'Servotronics, Inc.',
                'ticker': 'SVT'},
               {'currency': 'USD', 'name': 'FirstEnergy Corp.', 'ticker': 'FE'},
               {'currency': 'USD',
                'name': 'Pacific Gas & Electric Co.',
                'ticker': 'PCG'},
               {'currency': 'USD',
                'name': 'The York Water Company',
                'ticker': 'YORW'},
               {'currency': 'USD', 'name': 'UGI Corporation', 'ticker': 'UGI'},
               {'currency': 'USD',
                'name': 'GTT Communications, Inc.',
                'ticker': 'GTT'},
               {'currency': 'USD',
                'name': 'Huaneng Power Intl',
                'ticker': 'HNP'}]}
